apiVersion: v2
name: hmc
version: 0.0.5
icon: https://github.com/hmcts/chart-hmc/raw/master/images/icons8-java-50.png
keywords:
  - hmc
dependencies:
  - name: hmc-hmi-inbound-adapter
    version: 0.1.21
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: hmc.inboundAdapter.enabled

  - name: hmc-hmi-outbound-adapter
    version: 0.1.18
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: hmc.outboundAdapter.enabled

  - name: hmc-cft-hearing-service
    version: 1.6.23
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: hmc.hearingService.enabled

  - name: servicebus
    version: 1.2.1
    repository: 'oci://hmctspublic.azurecr.io/helm'
