hmc:
  inboundAdapter:
    enabled: true
  outboundAdapter:
    enabled: true
  s2s:
    enabled: true
  servicebus:
    enabled: true
  hearingService:
    enabled: true

global:
  idamApiUrl: ""
  idamWebUrl: ""
  s2sUrl: "http://{{ .Release.Name }}-s2s"

hmc-hmi-inbound-adapter:
  java:
    image: 'hmctspublic.azurecr.io/hmc/hmi-inbound-adapter:latest'
    imagePullPolicy: Always
    ingressHost: ""
    releaseNameOverride: "{{ .Release.Name }}-hmc-hmi-inbound-adapter"
    readinessDelay: 240
    livenessDelay: 240
    environment:
      HMC_SERVICE_BUS_QUEUE: hmc-from-hmi
      CFT_HEARING_SERVICE_URL: http://hmc-cft-hearing-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
      IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
      S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    secrets:
      HMC_SERVICE_BUS_CONNECTION_STRING:
        secretRef: servicebus-secret-queue-{{ .Release.Name }}-servicebus-hmc-from-hmi
        key: connectionString

hmc-hmi-outbound-adapter:
  java:
    image: 'hmctspublic.azurecr.io/hmc/hmi-outbound-adapter:latest'
    imagePullPolicy: Always
    ingressHost: ""
    releaseNameOverride: "{{ .Release.Name }}-hmc-hmi-outbound-adapter"
    readinessDelay: 240
    livenessDelay: 240
    environment:
      HMC_SERVICE_BUS_OUTBOUND_QUEUE: hmc-to-hmi
      HMC_SERVICE_BUS_INBOUND_QUEUE: hmc-from-hmi
      CFT_HEARING_SERVICE_DB_HOST: "{{ .Release.Name }}-postgresql"
      CFT_HEARING_SERVICE_DB_NAME: "{{ .Values.postgresql.auth.database}}"
      CFT_HEARING_SERVICE_DB_USERNAME: "{{ .Values.postgresql.auth.username}}"
      CFT_HEARING_SERVICE_DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
      CFT_HEARING_SERVICE_DB_OPTIONS: "?stringtype=unspecified"
      CFT_HEARING_SERVICE_DB_PORT: 5432
    secrets:
      HMC_SERVICE_BUS_OUTBOUND_CONNECTION_STRING:
        secretRef: servicebus-secret-queue-{{ .Release.Name }}-servicebus-hmc-to-hmi
        key: connectionString
      HMC_SERVICE_BUS_INBOUND_CONNECTION_STRING:
        secretRef: servicebus-secret-queue-{{ .Release.Name }}-servicebus-hmc-from-hmi
        key: connectionString

hmc-cft-hearing-service:
  java:
    image: 'hmctspublic.azurecr.io/hmc/cft-hearing-service:latest'
    imagePullPolicy: Always
    ingressHost: ""
    releaseNameOverride: "{{ .Release.Name }}-hmc-cft-hearing-service"
    readinessDelay: 240
    livenessDelay: 240
    postgresql:
      enabled: true
    environment:
      HMC_SERVICE_BUS_TOPIC: hmc-to-cft
      HMC_SERVICE_BUS_SUBSCRIPTION: hmc-subs-to-cft
      HMC_SERVICE_BUS_QUEUE: hmc-from-hmi
      HMC_OUTBOUND_SERVICE_BUS_QUEUE: hmc-to-hmi
      IDAM_OIDC_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
      OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
      IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
      S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
      CCD_DATA_STORE_API_BASE_URL: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
      ROLE_ASSIGNMENT_URL: http://am-role-assignment-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
      CFT_HEARING_SERVICE_DB_HOST: "{{ .Release.Name }}-postgresql"
      CFT_HEARING_SERVICE_DB_NAME: "{{ .Values.postgresql.auth.database}}"
      CFT_HEARING_SERVICE_DB_USERNAME: "{{ .Values.postgresql.auth.username}}"
      CFT_HEARING_SERVICE_DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
      CFT_HEARING_SERVICE_DB_OPTIONS: "?stringtype=unspecified"
      CFT_HEARING_SERVICE_DB_PORT: 5432
    secrets:
      HMC_SERVICE_BUS_CONNECTION_STRING:
        secretRef: servicebus-secret-topic-{{ .Release.Name }}-servicebus-hmc-to-cft
        key: connectionString
      HMC_QUEUE_CONNECTION_STRING:
        secretRef: servicebus-secret-queue-{{ .Release.Name }}-servicebus-hmc-from-hmi
        key: connectionString
      HMC_OUTBOUND_QUEUE_CONNECTION_STRING:
        secretRef: servicebus-secret-queue-{{ .Release.Name }}-servicebus-hmc-to-hmi
        key: connectionString

servicebus:
  enabled: true
  tags:
    teamName: "CDM"
    applicationName: "core-case-data"
    builtFrom: "https://github.com/hmcts/chart-hmc"
    businessArea: "CFT"
    environment: "development"
  resourceGroup: hmc-aks
  serviceplan: standard
  setup:
    topics:
      - name: hmc-to-cft
    subscriptions:
      - name: hmc-subs-to-cft
    queues:
      - name: hmc-from-hmi
      - name: hmc-to-hmi

